### PR TITLE
Add use case diagram and list of security requirements derived

### PR DESCRIPTION
**Pull request by jschrack**

### CODE REVIEW

**Review by peachykeen00 — CHANGES_REQUESTED** [review]
Hey Jesse! Nice work! This is a very detailed diagram. A few suggestions.... the SQL injection does not have a "threaten" designator for the use case. I'd recommend just removing it and it's attached relationships altogether. I'd also maybe remove some of the redundant security requirements such as the indirect references and MFA for simplification/decluttering purposes. I did this on my diagram as well because there are a plethora of misuse cases and security requirements that can be addressed for each situation, but my diagram continued to look busy and I kept thinking back to one of my take-aways from our meeting with Dr. Gandhi, which was "simplify". Maybe I'm overthinking in the opposite direction now and overcompensated, so adjust as you see fit. Nice thorough analysis though!

**Comment by jschrack** [comment]
@peachykeen00 Thanks for the comments. I definitely missed the threatens relationship between SQL injection and the use case. I'll consider adding the relationship or removing it from the diagram.

I'll also tidy up the diagram. I wanted to elicit as many security requirements as possible to find potential missing security features

**Comment by peachykeen00** [comment]
Sounds like a great plan! Just a reminder to also update the security requirements section of the file if you do remove any from your misuse case analysis.

**Review by peachykeen00 — APPROVED** [review]
Beautiful!

**Pull request merged**
