### PR TITLE
add rough draft of assurance case

### PR DESCRIPTION
**Pull request by jschrack**

### CODE REVIEW

**Review by peachykeen00 — CHANGES_REQUESTED** [review]
I think this is actually a good product. Suggestions for updates are as follows:
1. Reword your Top Claim per our Zoom session with Dr. Gandhi today.
2. Remove verb phrasing from Evidence (E1= Security reports, E2=Certificate logs)
3. Ideas for E3 are: Error Logs, Network Traffic Analysis, or Source Code Analysis)

**Comment by jschrack** [comment]
I have made changes for each of the above bullet points. Let me know if something still needs fixed. I appreciate the review.

**Review by peachykeen00 — CHANGES_REQUESTED** [review]
Minor additional update... check numbering scheme on sub-claims and rebuttals.

**Comment by jschrack** [comment]
> Minor additional update... check numbering scheme on sub-claims and rebuttals.

Resolved

**Review by peachykeen00 — APPROVED** [review]
Nice work!

**Pull request merged**
